export enum AuthErrorCode {

  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',

  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',

  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',

  AUTH_REFRESH_TOKEN_REUSED = 'AUTH_REFRESH_TOKEN_REUSED',

  AUTH_PASSWORD_CHANGE_REQUIRED = 'AUTH_PASSWORD_CHANGE_REQUIRED',

  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  AUTH_ORIGIN_NOT_ALLOWED = 'AUTH_ORIGIN_NOT_ALLOWED',

  AUTH_CSRF_TOKEN_INVALID = 'AUTH_CSRF_TOKEN_INVALID',

}